FROM nginx:alpine

# Copy all frontend files
COPY html/ /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/

# Replace default NGINX config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
